// src/symbols.js
export const TOP50 = [
  'MSFT','NVDA','AAPL','AMZN','META','AVGO','TSLA','GOOGL','BRK.B','GOOG',
  'JPM','V','LLY','NFLX','MA','XOM','COST','WMT','PG','HD',
  'JNJ','ABBV','BAC','CRM','KO','PM','PLTR','ORCL','CSCO','UNH',
  'WFC','IBM','GE','CVX','ABT','MCD','LIN','NOW','DIS','ACN',
  'ISRG','T','GS','MRK','UBER','AMD','INTU','VZ','RTX','PEP'
];

export const SYMBOL_NAME_MAP = {
  MSFT: 'Microsoft Corporation',
  NVDA: 'NVIDIA Corporation',
  AAPL: 'Apple Inc.',
  AMZN: 'Amazon.com, Inc.',
  META: 'Meta Platforms, Inc.',
  AVGO: 'Broadcom Inc.',
  TSLA: 'Tesla, Inc.',
  GOOGL: 'Alphabet Inc. (Class A)',
  'BRK.B': 'Berkshire Hathaway Inc. (Class B)',
  GOOG: 'Alphabet Inc. (Class C)',
  JPM: 'JPMorgan Chase & Co.',
  V: 'Visa Inc.',
  LLY: 'Eli Lilly and Company',
  NFLX: 'Netflix, Inc.',
  MA: 'Mastercard Incorporated',
  XOM: 'Exxon Mobil Corporation',
  COST: 'Costco Wholesale Corporation',
  WMT: 'Walmart Inc.',
  PG: 'The Procter & Gamble Company',
  HD: 'The Home Depot, Inc.',
  JNJ: 'Johnson & Johnson',
  ABBV: 'AbbVie Inc.',
  BAC: 'Bank of America Corporation',
  CRM: 'Salesforce, Inc.',
  KO: 'The Coca-Cola Company',
  PM: 'Philip Morris International Inc.',
  PLTR: 'Palantir Technologies Inc.',
  ORCL: 'Oracle Corporation',
  CSCO: 'Cisco Systems, Inc.',
  UNH: 'UnitedHealth Group Incorporated',
  WFC: 'Wells Fargo & Company',
  IBM: 'International Business Machines Corporation',
  GE: 'General Electric Company',
  CVX: 'Chevron Corporation',
  ABT: 'Abbott Laboratories',
  MCD: 'McDonald’s Corporation',
  LIN: 'Linde plc',
  NOW: 'ServiceNow, Inc.',
  DIS: 'The Walt Disney Company',
  ACN: 'Accenture plc',
  ISRG: 'Intuitive Surgical, Inc.',
  T: 'AT&T Inc.',
  GS: 'The Goldman Sachs Group, Inc.',
  MRK: 'Merck & Co., Inc.',
  UBER: 'Uber Technologies, Inc.',
  AMD: 'Advanced Micro Devices, Inc.',
  INTU: 'Intuit Inc.',
  VZ: 'Verizon Communications Inc.',
  RTX: 'RTX Corporation',
  PEP: 'PepsiCo, Inc.'
};
